#!/usr/bin/env bash
# Vue Component Analyzer - Usage Examples

echo "════════════════════════════════════════════════════════════════════════════"
echo "  VUE COMPONENT STRUCTURE ANALYZER - USAGE GUIDE"
echo "════════════════════════════════════════════════════════════════════════════"
echo ""

echo "📋 OVERVIEW"
echo "───────────────────────────────────────────────────────────────────────────"
echo ""
echo "This skill analyzes Vue 3 SFC components for:"
echo "  • Performance bottlenecks (v-for keys, complex expressions, watchers)"
echo "  • Code duplication (repeated utility methods, loading patterns)"
echo "  • Structural issues (large setup functions, excessive returns)"
echo "  • Cross-file patterns (duplicated logic across components)"
echo ""

echo "🚀 QUICK START"
echo "───────────────────────────────────────────────────────────────────────────"
echo ""
echo "1. Run analyzer:"
echo "   $ python scripts/analyze_vue.py"
echo ""
echo "2. View console report (summary of all issues)"
echo "   Outputs to stdout - pipe to file if needed:"
echo "   $ python scripts/analyze_vue.py > analysis.txt"
echo ""
echo "3. Review detailed JSON report:"
echo "   $ cat scripts/vue-analysis-report.json | jq '.summary'"
echo ""
echo "4. Get quick-fix guide:"
echo "   $ python scripts/quick_fix.py"
echo ""

echo "📊 OUTPUT FORMATS"
echo "───────────────────────────────────────────────────────────────────────────"
echo ""
echo "Console Report:"
echo "  ✓ Human-readable summary"
echo "  ✓ Issues grouped by severity (ERROR/WARNING/INFO)"
echo "  ✓ Category breakdown"
echo "  ✓ Top optimization opportunities"
echo "  ✓ Component metrics"
echo ""
echo "JSON Report (scripts/vue-analysis-report.json):"
echo "  ✓ Machine-parseable format"
echo "  ✓ All issues with line numbers"
echo "  ✓ Component metrics"
echo "  ✓ Suitable for CI/CD integration"
echo ""

echo "🎯 EXAMPLE WORKFLOWS"
echo "───────────────────────────────────────────────────────────────────────────"
echo ""
echo "Scenario 1: First-time analysis"
echo "  $ python scripts/analyze_vue.py"
echo "  $ python scripts/quick_fix.py  # See recommendations"
echo "  → Read OPTIMIZATION_GUIDE.md for detailed roadmap"
echo ""
echo "Scenario 2: Check specific component"
echo "  $ cat scripts/vue-analysis-report.json | jq '.issues[] | select(.file | contains(\"Dashboard\")'"
echo "  → See all issues for Dashboard.vue"
echo ""
echo "Scenario 3: Track improvement over time"
echo "  $ python scripts/analyze_vue.py > analysis_\$(date +%Y%m%d).txt"
echo "  $ diff analysis_20260624.txt analysis_20260625.txt"
echo "  → Compare issue count and severity changes"
echo ""
echo "Scenario 4: Fix critical issues only"
echo "  $ cat scripts/vue-analysis-report.json | jq '.issues[] | select(.severity == \"error\")'"
echo "  → Show only ERROR severity issues"
echo "  $ python scripts/quick_fix.py  # Provides fix instructions"
echo ""

echo "📈 KEY METRICS"
echo "───────────────────────────────────────────────────────────────────────────"
echo ""
echo "Watch these metrics to track improvement:"
echo ""
echo "  Total Issues      Current: 59  →  Target: <10"
echo "  Errors            Current: 3   →  Target: 0"
echo "  Warnings          Current: 3   →  Target: <3"
echo "  Avg Setup Size    Current: 232 →  Target: <150"
echo "  Watchers/Comp     Current: 8/19 → Target: <5/19"
echo ""

echo "🔍 ISSUE CATEGORIES"
echo "───────────────────────────────────────────────────────────────────────────"
echo ""
echo "Performance (5 issues):"
echo "  • v-for without :key"
echo "  • v-for with index as :key"
echo "  • v-if + v-for on same element"
echo "  • Complex template expressions"
echo "  • Redundant watchers"
echo ""
echo "Code Reuse (50 issues):"
echo "  • Duplicated utility methods"
echo "  • Shared state patterns → composable candidates"
echo "  • Repeated loading patterns"
echo ""
echo "Structure (4 issues):"
echo "  • Large setup functions (>150 lines)"
echo "  • Oversized return objects (>20 properties)"
echo "  • Too many component imports (>5)"
echo ""

echo "📋 ANALYSIS DETAILS"
echo "───────────────────────────────────────────────────────────────────────────"
echo ""
echo "Files Analyzed: 19 components"
echo "  • 1 root component (App.vue)"
echo "  • 11 reusable components (in components/)"
echo "  • 7 page views (in views/)"
echo ""
echo "Analysis Coverage:"
echo "  ✓ Template syntax issues"
echo "  ✓ Script structure problems"
echo "  ✓ Cross-component duplication"
echo "  ✓ Missing optimizations"
echo ""

echo "⚡ PERFORMANCE IMPACT"
echo "───────────────────────────────────────────────────────────────────────────"
echo ""
echo "Fixing all recommendations would provide:"
echo ""
echo "  Bundle Size:"
echo "    • Remove 10+ KB of duplicate code"
echo "    • Improved tree-shaking with composables"
echo "    • Estimated: 2-5% reduction"
echo ""
echo "  Runtime:"
echo "    • Fix v-for reactivity issues → faster updates"
echo "    • Extract complex expressions → less render work"
echo "    • Better component reuse → smaller VDOM trees"
echo "    • Estimated: 10-15% faster initial render"
echo ""
echo "  Maintainability:"
echo "    • 40% less code in large components"
echo "    • 8 new reusable composables"
echo "    • Clear separation of concerns"
echo ""

echo "📚 DOCUMENTATION FILES"
echo "───────────────────────────────────────────────────────────────────────────"
echo ""
echo "  • OPTIMIZATION_GUIDE.md"
echo "    └─ Detailed roadmap, 4-week implementation plan, architecture"
echo ""
echo "  • scripts/README_ANALYZER.md"
echo "    └─ Analyzer features, rules, usage, integration guide"
echo ""
echo "  • scripts/analyze_vue.py"
echo "    └─ 600+ lines of analysis engine (SFC parser, rule checks, reporter)"
echo ""
echo "  • scripts/quick_fix.py"
echo "    └─ Quick-start guide and auto-fix tool"
echo ""

echo "🤖 CI/CD INTEGRATION"
echo "───────────────────────────────────────────────────────────────────────────"
echo ""
echo "In your CI pipeline:"
echo ""
echo "  # Fail on critical issues"
echo "  python scripts/analyze_vue.py"
echo "  if [ \$? -eq 1 ]; then"
echo "    echo \"Critical Vue issues found. See scripts/vue-analysis-report.json\""
echo "    exit 1"
echo "  fi"
echo ""
echo "In pre-commit hook:"
echo ""
echo "  #!/bin/bash"
echo "  # Run analyzer on changed Vue files"
echo "  git diff --name-only --cached | grep '\\.vue$'"
echo "  if [ \$? -eq 0 ]; then"
echo "    python scripts/analyze_vue.py"
echo "  fi"
echo ""

echo "💡 TIPS & TRICKS"
echo "───────────────────────────────────────────────────────────────────────────"
echo ""
echo "1. Focus on errors first (3 critical issues)"
echo "   $ cat scripts/vue-analysis-report.json | jq '.issues[] | select(.severity==\"error\")'"
echo ""
echo "2. Track improvements with Git"
echo "   $ git diff HEAD~1 scripts/vue-analysis-report.json"
echo ""
echo "3. Extract the worst offenders"
echo "   $ cat scripts/vue-analysis-report.json | jq '.metrics | sort_by(.unique_issues) | reverse | .[0:5]'"
echo ""
echo "4. Verify fixes"
echo "   $ python scripts/analyze_vue.py | grep -c 'Total Issues'"
echo "   (should decrease after each fix)"
echo ""

echo "🎓 LEARNING RESOURCES"
echo "───────────────────────────────────────────────────────────────────────────"
echo ""
echo "Vue 3 Composition API:"
echo "  https://vuejs.org/guide/extras/composition-api-faq.html"
echo ""
echo "Composables:"
echo "  https://vuejs.org/guide/reusability/composables.html"
echo ""
echo "Performance:"
echo "  https://vuejs.org/guide/best-practices/performance.html"
echo ""
echo "List Rendering (v-for best practices):"
echo "  https://vuejs.org/guide/essentials/list.html#key"
echo ""

echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo ""
echo "Questions? See:"
echo "  • OPTIMIZATION_GUIDE.md (detailed recommendations)"
echo "  • scripts/README_ANALYZER.md (technical details)"
echo "  • scripts/vue-analysis-report.json (full data)"
echo ""
